[workspace]

[package]
name = "kg-wasm-example"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
kg-core  = { path = "../../crates/kg-core" }
kg-neo4j = { path = "../../crates/kg-neo4j", default-features = false, features = ["wasm"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["console"] }
